create table refresh_token_sessions (
    refresh_token_session_id bigint generated by default as identity primary key,
    user_id bigint not null,
    token_hash varchar(64) not null,
    family_id varchar(36) not null,
    expires_at timestamp(6) with time zone not null,
    revoked_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    constraint uk_refresh_token_sessions_token_hash unique (token_hash)
);

create index idx_refresh_token_sessions_family_id on refresh_token_sessions (family_id);
create index idx_refresh_token_sessions_user_id on refresh_token_sessions (user_id);
