create table users (
    user_id bigint generated by default as identity primary key,
    email varchar(255) not null,
    password varchar(255) not null,
    nickname varchar(100) not null,
    name varchar(100),
    profile_image_url text,
    profile_image_object_key varchar(1024),
    points bigint not null,
    role varchar(20) not null,
    grade varchar(20) not null,
    status varchar(20) not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    constraint uk_users_email unique (email),
    constraint uk_users_nickname unique (nickname)
);

create index idx_users_profile_image_object_key
    on users (profile_image_object_key)
    where profile_image_object_key is not null;

create table refresh_token_sessions (
    refresh_token_session_id bigint generated by default as identity primary key,
    user_id bigint not null,
    token_hash varchar(64) not null,
    family_id varchar(36) not null,
    expires_at timestamp(6) with time zone not null,
    revoked_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    constraint uk_refresh_token_sessions_token_hash unique (token_hash),
    constraint fk_refresh_token_sessions_user
        foreign key (user_id) references users (user_id)
);

create index idx_refresh_token_sessions_family_id on refresh_token_sessions (family_id);
create index idx_refresh_token_sessions_user_id on refresh_token_sessions (user_id);

create table social_accounts (
    social_account_id bigint generated by default as identity primary key,
    user_id bigint not null,
    provider varchar(20) not null,
    provider_user_id varchar(100) not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    constraint uk_social_accounts_provider_provider_user_id unique (provider, provider_user_id),
    constraint fk_social_accounts_user
        foreign key (user_id) references users (user_id)
);

create index idx_social_accounts_user_id on social_accounts (user_id);

create table posts (
    post_id bigint generated by default as identity primary key,
    user_id bigint not null,
    title varchar(500) not null,
    prompt_body text,
    thumbnail_image_url varchar(500),
    output_type varchar(20),
    description text,
    content_type varchar(20),
    status varchar(20) not null,
    visibility varchar(20) not null,
    price_point bigint,
    hidden_reason varchar(255),
    hidden_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    constraint fk_posts_user foreign key (user_id) references users (user_id),
    constraint ck_posts_visibility check (visibility in ('PUBLIC', 'PRIVATE'))
);

create index idx_posts_user_id on posts (user_id);
create unique index uk_posts_user_live_draft
    on posts (user_id)
    where status = 'DRAFT' and deleted_at is null;

create table tags (
    tag_id bigint generated by default as identity primary key,
    tag_type varchar(20) not null,
    tag_name varchar(100) not null,
    normalized_name varchar(100),
    is_custom boolean,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    constraint uk_tags_type_name unique (tag_type, tag_name),
    constraint uk_tags_type_normalized_name unique (tag_type, normalized_name)
);

insert into tags (tag_type, tag_name, normalized_name, is_custom, created_at, updated_at)
values
    ('JOB', '학생', '학생', false, current_timestamp, current_timestamp),
    ('JOB', '직장인', '직장인', false, current_timestamp, current_timestamp),
    ('JOB', '자영업자', '자영업자', false, current_timestamp, current_timestamp),
    ('JOB', '기획자', '기획자', false, current_timestamp, current_timestamp),
    ('JOB', '디자이너', '디자이너', false, current_timestamp, current_timestamp),
    ('JOB', '개발자', '개발자', false, current_timestamp, current_timestamp),
    ('TASK', 'PPT', 'ppt', false, current_timestamp, current_timestamp),
    ('TASK', '레포트', '레포트', false, current_timestamp, current_timestamp),
    ('TASK', '이메일', '이메일', false, current_timestamp, current_timestamp),
    ('TASK', '보고서', '보고서', false, current_timestamp, current_timestamp),
    ('TASK', '회의록', '회의록', false, current_timestamp, current_timestamp),
    ('TASK', '이미지 생성', '이미지 생성', false, current_timestamp, current_timestamp);

create table user_interest_tags (
    user_id bigint not null,
    tag_id bigint not null,
    primary key (user_id, tag_id),
    constraint fk_user_interest_tags_user foreign key (user_id) references users (user_id),
    constraint fk_user_interest_tags_tag foreign key (tag_id) references tags (tag_id)
);

create index idx_user_interest_tags_tag_id on user_interest_tags (tag_id);

create table post_tags (
    post_id bigint not null,
    tag_id bigint not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    primary key (post_id, tag_id),
    constraint fk_post_tags_post foreign key (post_id) references posts (post_id),
    constraint fk_post_tags_tag foreign key (tag_id) references tags (tag_id)
);

create index idx_post_tags_tag_id on post_tags (tag_id);

create table prompt_images (
    prompt_image_id uuid primary key,
    uploader_id bigint not null,
    prompt_id bigint,
    original_object_key varchar(1024) not null,
    watermarked_object_key varchar(1024),
    original_file_name varchar(255) not null,
    content_type varchar(10) not null,
    file_size bigint not null,
    width integer not null,
    height integer not null,
    etag varchar(255),
    uploaded_at timestamp(6) with time zone,
    status varchar(20) not null,
    processing_version integer not null default 0,
    failure_code varchar(100),
    sort_order integer,
    is_thumbnail boolean not null default false,
    lock_version bigint not null default 0,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    constraint uk_prompt_images_original_object_key unique (original_object_key),
    constraint uk_prompt_images_watermarked_object_key unique (watermarked_object_key),
    constraint uk_prompt_images_prompt_sort_order unique (prompt_id, sort_order),
    constraint fk_prompt_images_uploader foreign key (uploader_id) references users (user_id),
    constraint fk_prompt_images_prompt foreign key (prompt_id) references posts (post_id),
    constraint ck_prompt_images_content_type check (content_type in ('JPEG', 'PNG')),
    constraint ck_prompt_images_file_size check (file_size > 0 and file_size <= 10485760),
    constraint ck_prompt_images_dimensions check (
        width > 0
        and height > 0
        and width <= 8192
        and height <= 8192
        and cast(width as bigint) * cast(height as bigint) <= 40000000
    ),
    constraint ck_prompt_images_status
        check (status in ('UPLOADING', 'UPLOADED', 'PROCESSING', 'READY', 'FAILED')),
    constraint ck_prompt_images_processing_version check (processing_version >= 0),
    constraint ck_prompt_images_state_payload check (
        (status = 'UPLOADING'
            and etag is null
            and uploaded_at is null
            and watermarked_object_key is null
            and failure_code is null
            and processing_version = 0)
        or (status = 'UPLOADED'
            and etag is not null
            and uploaded_at is not null
            and watermarked_object_key is null
            and failure_code is null
            and processing_version = 0)
        or (status = 'PROCESSING'
            and ((etag is null and uploaded_at is null) or (etag is not null and uploaded_at is not null))
            and watermarked_object_key is null
            and failure_code is null
            and processing_version = 0)
        or (status = 'READY'
            and ((etag is null and uploaded_at is null) or (etag is not null and uploaded_at is not null))
            and watermarked_object_key is not null
            and watermarked_object_key <> original_object_key
            and processing_version > 0
            and failure_code is null)
        or (status = 'FAILED'
            and ((etag is null and uploaded_at is null) or (etag is not null and uploaded_at is not null))
            and watermarked_object_key is null
            and failure_code is not null
            and processing_version = 0)
    ),
    constraint ck_prompt_images_attachment check (
        (prompt_id is null and sort_order is null and is_thumbnail = false)
        or (prompt_id is not null and sort_order is not null and sort_order >= 0 and status = 'READY')
    )
);

create index idx_prompt_images_uploader_status on prompt_images (uploader_id, status);
create index idx_prompt_images_prompt_id on prompt_images (prompt_id);
create index idx_prompt_images_status_created_at on prompt_images (status, created_at);

create table prompt_image_watermark_outbox (
    event_id uuid primary key,
    image_id uuid not null,
    event_type varchar(100) not null,
    event_version integer not null,
    processing_version integer not null,
    payload text not null,
    status varchar(20) not null,
    attempt_count integer not null default 0,
    available_at timestamp(6) with time zone not null,
    published_at timestamp(6) with time zone,
    last_error varchar(1000),
    lock_version bigint not null default 0,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    constraint fk_prompt_image_watermark_outbox_image
        foreign key (image_id) references prompt_images (prompt_image_id) on delete cascade,
    constraint uk_prompt_image_watermark_outbox_image_version unique (image_id, processing_version),
    constraint ck_prompt_image_watermark_outbox_event_version check (event_version > 0),
    constraint ck_prompt_image_watermark_outbox_processing_version check (processing_version > 0),
    constraint ck_prompt_image_watermark_outbox_status check (status in ('PENDING', 'PUBLISHED')),
    constraint ck_prompt_image_watermark_outbox_attempt_count check (attempt_count >= 0),
    constraint ck_prompt_image_watermark_outbox_publish_state check (
        (status = 'PENDING' and published_at is null)
        or (status = 'PUBLISHED' and published_at is not null)
    )
);

create index idx_prompt_image_watermark_outbox_publish
    on prompt_image_watermark_outbox (status, available_at, created_at);

create table post_statistics (
    post_id bigint primary key,
    view_count bigint not null,
    copy_count bigint not null,
    like_count bigint not null,
    report_count bigint not null,
    comment_count bigint not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    constraint fk_post_statistics_post foreign key (post_id) references posts (post_id)
);

create table comments (
    comment_id bigint generated by default as identity primary key,
    post_id bigint not null,
    user_id bigint not null,
    content text not null,
    status varchar(20) not null,
    parent_comment_id bigint,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    constraint fk_comments_post foreign key (post_id) references posts (post_id),
    constraint fk_comments_user foreign key (user_id) references users (user_id),
    constraint fk_comments_parent foreign key (parent_comment_id) references comments (comment_id)
);

create index idx_comments_post_id_created_at on comments (post_id, created_at);
create index idx_comments_user_id on comments (user_id);
create index idx_comments_parent_comment_id on comments (parent_comment_id);

create table post_interactions (
    interaction_id bigint generated by default as identity primary key,
    user_id bigint not null,
    post_id bigint not null,
    interaction_type varchar(20) not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    constraint uk_post_interactions_user_post_type unique (user_id, post_id, interaction_type),
    constraint fk_post_interactions_user foreign key (user_id) references users (user_id),
    constraint fk_post_interactions_post foreign key (post_id) references posts (post_id)
);

create index idx_post_interactions_post_id on post_interactions (post_id);

create table point_histories (
    point_history_id bigint generated by default as identity primary key,
    user_id bigint not null,
    point_transaction_type varchar(40) not null,
    amount bigint not null,
    balance_after bigint not null,
    reference_type varchar(50),
    reference_id bigint,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    constraint fk_point_histories_user foreign key (user_id) references users (user_id)
);

create index idx_point_histories_user_id on point_histories (user_id);

create table post_unlocks (
    post_unlock_id bigint generated by default as identity primary key,
    post_id bigint not null,
    user_id bigint not null,
    creator_user_id bigint not null,
    paid_point bigint not null,
    creator_reward_point bigint not null,
    unlocked_at timestamp(6) with time zone not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    constraint uk_post_unlocks_user_post unique (user_id, post_id),
    constraint fk_post_unlocks_post foreign key (post_id) references posts (post_id),
    constraint fk_post_unlocks_user foreign key (user_id) references users (user_id),
    constraint fk_post_unlocks_creator foreign key (creator_user_id) references users (user_id)
);

create index idx_post_unlocks_post_id on post_unlocks (post_id);
create index idx_post_unlocks_creator_user_id on post_unlocks (creator_user_id);

create table post_copies (
    post_copy_id bigint generated by default as identity primary key,
    user_id bigint not null,
    post_id bigint not null,
    copied_at timestamp(6) with time zone not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    constraint uk_post_copies_user_post unique (user_id, post_id),
    constraint fk_post_copies_user foreign key (user_id) references users (user_id),
    constraint fk_post_copies_post foreign key (post_id) references posts (post_id)
);

create index idx_post_copies_post_id on post_copies (post_id);

create table post_reports (
    report_id bigint generated by default as identity primary key,
    reporter_id bigint not null,
    post_id bigint not null,
    reason varchar(30) not null,
    description text not null,
    status varchar(20) not null default 'PENDING',
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    constraint uk_post_reports_user_post unique (reporter_id, post_id),
    constraint fk_post_reports_reporter foreign key (reporter_id) references users (user_id),
    constraint fk_post_reports_post foreign key (post_id) references posts (post_id)
);

create index idx_post_reports_post_id on post_reports (post_id);

create table comment_reports (
    report_id bigint generated by default as identity primary key,
    reporter_id bigint not null,
    comment_id bigint not null,
    reason varchar(30) not null,
    description text not null,
    status varchar(20) not null default 'PENDING',
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    constraint uk_comment_reports_user_comment unique (reporter_id, comment_id),
    constraint fk_comment_reports_reporter foreign key (reporter_id) references users (user_id),
    constraint fk_comment_reports_comment foreign key (comment_id) references comments (comment_id)
);

create index idx_comment_reports_comment_id on comment_reports (comment_id);

create table event_logs (
    log_id bigint generated by default as identity primary key,
    user_id bigint,
    event_name varchar(100) not null,
    anonymous_id varchar(100),
    session_id varchar(100) not null,
    target_type varchar(30),
    target_id bigint,
    properties text,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone
);

-- event_logs.user_id와 다형 참조인 target_id, point_histories.reference_id는
-- 로그 보존 및 참조 대상 다양성을 위해 의도적으로 FK를 적용하지 않는다.
