create table social_accounts (
    social_account_id bigint generated by default as identity primary key,
    user_id bigint not null,
    provider varchar(20) not null,
    provider_user_id varchar(100) not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    constraint uk_social_accounts_provider_provider_user_id unique (provider, provider_user_id)
);

create index idx_social_accounts_user_id on social_accounts (user_id);
