create table user_agreements (
    user_agreement_id bigint generated by default as identity primary key,
    user_id bigint not null,
    agreement_type varchar(50) not null,
    agreement_version varchar(50) not null,
    agreed boolean not null,
    agreed_at timestamp(6) with time zone not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    constraint fk_user_agreements_user foreign key (user_id) references users (user_id)
);
create index idx_user_agreements_user_id_agreed_at on user_agreements (user_id, agreed_at);
