update users
set grade = 'NODE'
where grade = 'NORMAL';

create table grade_requests (
    grade_request_id bigint generated by default as identity primary key,
    user_id bigint not null,
    current_grade varchar(20) not null,
    requested_grade varchar(20) not null,
    status varchar(20) not null default 'PENDING',
    processed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    constraint fk_grade_requests_user foreign key (user_id) references users (user_id)
);

create index idx_grade_requests_user_id on grade_requests (user_id);
create index idx_grade_requests_status on grade_requests (status);
