CREATE TABLE IF NOT EXISTS post_reports (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    reason VARCHAR(30) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_post_reports_user_post UNIQUE (reporter_id, post_id)
);

CREATE TABLE IF NOT EXISTS comment_reports (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT NOT NULL,
    comment_id BIGINT NOT NULL,
    reason VARCHAR(30) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_comment_reports_user_comment UNIQUE (reporter_id, comment_id)
);

ALTER TABLE post_reports ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE post_reports ADD COLUMN IF NOT EXISTS reason VARCHAR(30);
UPDATE post_reports SET description = '기존 신고 데이터' WHERE description IS NULL;
UPDATE post_reports SET reason = 'ETC' WHERE reason IS NULL;
ALTER TABLE post_reports ALTER COLUMN description SET NOT NULL;
ALTER TABLE post_reports ALTER COLUMN reason SET NOT NULL;
ALTER TABLE post_reports ALTER COLUMN status SET DEFAULT 'PENDING';
